<a href="https://colab.research.google.com/github/Psalmist70/sms-phishing-detection/blob/main/notebooks/sms-phishing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [16]:
BASE_PATH = '/content/drive/MyDrive/sms-phishing-detection/dataset'

RAW_PATH = f'{BASE_PATH}/raw'
CLEANED_PATH = f'{BASE_PATH}/cleaned'

In [17]:
import pandas as pd

file_path = f'{RAW_PATH}/spam.csv'  # change this

df = pd.read_csv(file_path)
df.head()

UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 606-607: invalid continuation byte

In [5]:
# 👉 CHANGE THESE based on your dataset
label_col = 'Label'       # e.g. 'label', 'v1'
message_col = 'Message'     # e.g. 'message', 'text'

df = df[[label_col, message_col]]
df.columns = ['label', 'message']

In [6]:
df.head()

        label                                            message
0  legitimate  Debit\nAmt:NGN50,000.00\nAcc:171******903\nDes...
1  legitimate  Credit\nAmt:NGN10,000.00\nAcc:171******903\nDe...
2  legitimate  Debit\nAmt:NGN3,000.00\nAcc:171******903\nDesc...
3  legitimate  Debit\nAmt:NGN2,000.00\nAcc:171******903\nDesc...
4  legitimate  Debit\nAmt:NGN3,000.00\nAcc:171******903\nDesc...

In [7]:
df['label'] = df['label'].astype(str).str.lower().str.strip()

df['label'] = df['label'].replace({
    'spam': 1,
    'ham': 0,
    'smishing': 1,
    'legitimate': 0,
    '1': 1,
    '0': 0
})

df['label'] = df['label'].astype(int)

/tmp/ipykernel_26550/953889016.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['label'] = df['label'].replace({

In [8]:
df.head()

   label                                            message
0      0  Debit\nAmt:NGN50,000.00\nAcc:171******903\nDes...
1      0  Credit\nAmt:NGN10,000.00\nAcc:171******903\nDe...
2      0  Debit\nAmt:NGN3,000.00\nAcc:171******903\nDesc...
3      0  Debit\nAmt:NGN2,000.00\nAcc:171******903\nDesc...
4      0  Debit\nAmt:NGN3,000.00\nAcc:171******903\nDesc...

In [9]:
import re

def clean_text(text):
    text = str(text).lower()

    # Replace URLs with token (important for phishing detection)
    text = re.sub(r'http\S+|www\S+', ' URL ', text)

    # Remove extra spaces
    text = re.sub(r'\s+', ' ', text)

    return text.strip()

df['message'] = df['message'].apply(clean_text)

In [10]:
print(df['label'].value_counts())

label
0    200
1    200
Name: count, dtype: int64

In [12]:
df['source'] = 'core'  # change per dataset

In [13]:
df.head()

   label                                            message source
0      0  debit amt:ngn50,000.00 acc:171******903 desc:5...   core
1      0  credit amt:ngn10,000.00 acc:171******903 desc:...   core
2      0  debit amt:ngn3,000.00 acc:171******903 desc:51...   core
3      0  debit amt:ngn2,000.00 acc:171******903 desc:51...   core
4      0  debit amt:ngn3,000.00 acc:171******903 desc:51...   core

In [14]:
output_path = f'{CLEANED_PATH}/core_sms_cleaned_v1.csv'

df.to_csv(output_path, index=False)

In [15]:
df.info()
df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    400 non-null    int64
 1   message  400 non-null    object
 2   source   400 non-null    object
dtypes: int64(1), object(2)
memory usage: 9.5+ KB

   label                                            message source
0      0  debit amt:ngn50,000.00 acc:171******903 desc:5...   core
1      0  credit amt:ngn10,000.00 acc:171******903 desc:...   core
2      0  debit amt:ngn3,000.00 acc:171******903 desc:51...   core
3      0  debit amt:ngn2,000.00 acc:171******903 desc:51...   core
4      0  debit amt:ngn3,000.00 acc:171******903 desc:51...   core